.TH mandy 1
.SH NAME
mandy - Mandelbrot set drawer
.SH SYNOPSIS
.B mandy
.RI [ OPTIONS ]
.br
.B mandy
.RI [ OPTIONS ]
.B --draw
.I WIDTH
.I HEIGHT
.I X
.I Y
.I RADIUS
.I MAXITERS
.I PATH
.SH DESCRIPTION
.B mandy
draws images of the Mandelbrot set, with its complement colored
according to the escape time algorithm.
Optionally it displays the corresponding Julia set image.
.SH MOUSE
Double click at a point to zoom in on that point.  Hold control while
double clicking to zoom out.
.PP
Drag to move the displayed image without zooming.
.PP
If the Julia set window is displayed, click or drag with shift held
to, in the Mandelbrot set window, to set the Julia set parameter.
.SH KEYBOARD
Use control with + or minus to zoom in and out respectively.
.SH MENU
Using the
.B File
menu you can save the current Mandelbrot or Julia set image, close the
window, or quit the program.
.PP
The
.B Windows
menu allows you to create and destroy the Julia set window.
.SH "CONTROL PANEL"
The left side of the control panel contains two text entry boxes for
the centre of the
image and a third for the size.
All of these may be edited; press RETURN to commit to the new values.
The size is the radius of the biggest circle that fits on the display,
or (looked at another way) the size of the smaller dimension.
.PP
A fourth box on the left side allows the maximum iteration count to be adjusted.
.PP
The right side shows the position of the pointer and the number of
iterations reached at that point.
.PP
The \fBPrecision\fR dropdown allows the precision to be chosen from
the following:
.TP
.B double
Native floating point type.
.TP
.B simd2
Native floating point type, 2-way SIMD.
Availability depends on platform.
.TP
.B simd4
Native floating point type, 4-way SIMD.
Availability depends on platform.
.TP
.B "long double"
Native floating point type.
Provides more precision than \fBdouble\fR at a small performance cost.
.TP
.B fixed64
64-bit fixed point type.
Provides slightly more precision than \fBdouble\fR at a small
performance cost.
.TP
.B fixed128
128-bit fixed point type.
Provides much more precision than the other types at a relatively
large performance cost.
.PP
Relative performance depends on your hardware and whether the
assembler implementations of the underlying algorithm are used.
.SH OPTIONS
.TP
.B --help\fR, \fB-h
Display a usage message.
.TP
.B --threads \fITHREADS\fR, \fB-t \fITHREADS
Set the number of threads to use.
The default is the number of online CPU cores.
.TP
.B --draw
Draw a Mandelbrot set image and save it to a file.
.SH "OFFLINE DRAWING"
.SS Stills
The
.B --draw
option may be used to draw a single frame and save it to a file.
The syntax is:
.PP
.B mandy
.RI [ OPTIONS ]
.B --draw
.B --
.I WIDTH
.I HEIGHT
.I X
.I Y
.I RADIUS
.I MAXITERS
.I PATH
.TP
.B \(bu
.I WIDTH
and
.I HEIGHT
are the pixel size of the image.
.TP
.B \(bu
.I X
and
.I Y
are the real and imaginary coordinates of the centre of the image and
.I RADIUS
is the radius of the largest inscribed circle (equivalently, the
distance from the centre to the nearest edge).
.TP
.B \(bu
.I MAXITERS
is the maximum iteration count.
.TP
.B \(bu
.I PATH
is the name of the file to save to.
The file type is inferred from the extension, which can be one of
.BR .png ,
.B .ppm
or
.BR .jpeg .
.SS Movies
The
.B --dive
option may be used to create a video of a dive through the set.
The syntax is:
.PP
.B mandy
.RI [ OPTIONS ]
.B --dive
.B --
.I WIDTH
.I HEIGHT
.I START-X
.I START-Y
.I START-RADIUS
.I END-X
.I END-Y
.I END-RADIUS
.I MAXITERS
.I SECONDS
.I PATH
.PP
The radius progresses from \fISTART-RADIUS\fR to \fIEND-RADIUS\fR
exponentially, in other words giving a uniform zoom per frame
transition.
.PP
The centre location progresses from \fISTART-X\fR/\fIY\fR to
\fIEND-X\fR/\fIY\fR linearly.
This may be changed.
Until then, it is recommended that the start and end locations be the
same.
.PP
In addition the following environment variables may be set:
.TP
.B FFMPEG
The encoder to use.
The default is \fBavconf\fR if that is on the path, otherwise \fBffmpeg\fR.
.TP
.B FRAME_RATE
The frame rate.
The default is \fB25\fR.
.TP
.B BITRATE
The output bitrate.
The default is \fI2097152\fR.
.PP
Note that this option uses a temporary file for each frame in the
current directory.
.SH AUTHOR
Richard Kettlewell <rjk@greenend.org.uk>
