.TH mandy 1
.SH NAME
mandy - Mandelbrot set drawer
.SH SYNOPSIS
.B mandy
.SH DESCRIPTION
.B mandy
draws images of the Mandelbrot set, with its complement colored
according to the escape time algorithm.
Optionally it displays the corresponding Julia set image.
.SH "MOUSE CONTROLS"
Double click at a point to zoom in on that point.  Hold control while
double clicking to zoom out.
.PP
Drag to move the displayed image without zooming.
.PP
If the Julia set window is displayed, click or drag with shift held
to, in the Mandelbrot set window, to set the Julia set parameter.
.SH "KEYBOARD CONTROLS"
Use control with + or minus to zoom in and out respectively.
.SH AUTHOR
Richard Kettlewell <rjk@greenend.org.uk>
